- scripts/gen_onload_part.py
The parameters of the tested hosts depend on the specific site of use, and it would be better to save them and manage them in some internal storage
OL-Redmine-Id: 12239
Checked with both cases:
```shell
./gen_onload_part.py 1 1 <host-name>
./gen_onload_part.py 1 1 <host-name> --use-params-file=<path/to/separate/file.yml>
```
> scripts: allow to use separate file with hosts parameters

- scripts/gen_onload_part.py
Otherwise, the script will only work if the schema file exists in the current directory.
Fixes: 7fdb9bd3afc4 ("scripts: allow to use separate file with hosts parameters")
> scripts: use the absolute path for the yaml schema file

- sockapi-ts/basic/socket_via_af_unix_read.c
- sockapi-ts/basic/socket_via_af_unix_write.c
- sockapi-ts/level5/fd_caching/fd_cache_dup.c
- sockapi-ts/lib/sockapi-ts.c
- sockapi-ts/tcp/syn_sent_func.c
Recently TE has deprecated old and unsafe tapi_file_generate_name(). The patch replaces it with a proper replacement with no functional changes. Several occurrences of it are still retained in 'services' subdirectory, as the code there is never compiled anyway.
Signed-off-by: Artem Andreev <artem.andreev@oktetlabs.ru>
Testing Done: `./run.sh --cfg={our local cfg name} --tester-run=sockapi-ts/basic/socket_via_af_unix_read`. The patch does not change any runtime behaviour, so it can be verified on any configuration, incl. pure Linux.
> ts: replace deprecated file path functions with modern ones

- scripts/run.sh
The variable TE_ENV_IUT_EF_DUT has been renamed to TE_ENV_IUT_DUT since the sapi-ts, in general, can be run on network adapters from various manufacturers.
------------
Checked with the following command line (tests are running now):
```shell
./run.sh -n --cfg=<my-cfg> --ool=socket_cache --ool=onload \
--tester-run=sockapi-ts/level5/fd_caching/fd_cache_nonblock_sync:env=VAR.env.peer2peer_two_iut,use_libc=TRUE,check_first=FALSE,nonblock_first=TRUE,nonblock_func=fcntl,func=read
```
> scripts: follow changes in the ts-conf repository

- sockapi-ts/bpf/prologue.c
- sockapi-ts/congestion/prologue.c
- sockapi-ts/lib/sockapi-ts_bpf.c
- sockapi-ts/lib/sockapi-ts_bpf.h
The rlimits/memlock type was changed in TE from int32 to uint64.
-------------
Testing done:
The congestion/prologue is green now, but before this patch there is the following error:
```shell
Test Failed in ../../../sockapi-ts/lib/sockapi-ts_bpf.c, line 387, sockts_bpf_set_rlim_memlock()
line 387: cfg_get_instance_fmt(&val_t_int, &memlock_cur, "/agent:%s/rlimits:/memlock:/cur:", rpcs->ta)
returns 0x10400388 (CONF_API-EBADTYPE), but expected 0
```
> ts: use the proper variable type to work with memlock

- sockapi-ts/multicast/ip_multicast_if.c
- sockapi-ts/multicast/mcast_route.c
Pointer to cfg_val_type should be passed as an argument to cfg_get_instance() instead of a constant. Moreover here we use new function cfg_get_int32().
OL-Redmine-Id: 11890
Signed-off-by: Nikolai Kosovskii <nikolai.kosovskii@oktetlabs.ru>
---
Testing done:
Checked with sapi-ts running
`./run.sh -q --cfg=<my-cfg>  --build-only
`
https://github.com/oktetlabs/sapi-ts/commit/c58b64db60c6ed24b2d568cda521d2c49ac22ac6
> sockapi-ts/multicast: fix getting instance value

- conf/scripts/sockapi-ts
OL-Redmine-Id: 12265
Fixes: 44849548a0ea ("scripts: move processing hosts to a right place")
-----
Testing done:
- the `shellcheck --shell=bash --severity=warning conf/scripts/sockapi-ts` is silent now on these lines;
- the `SF_TS_TMPDIR` directory is created now on all hosts.
> conf/scripts: fix annoying typos

- scripts/gen_onload_part.py
- scripts/ool_fix_consistency.sh
- scripts/ool_fix_reqs.py
- scripts/ool_params_freqs.yaml
Testing done:
```shell
./gen_onload_part.py -a 1 1 <my-host> -x |grep af_xdp_single
for i in {1..100} ; do ./gen_onload_part.py -a $i 1 <my-host> -x |grep af_xdp ; done
```
> Rename the af_xdp_single option to af_xdp_no_filters and allow testing it on all NICs

- scripts/ool_fix_consistency.sh
Replace "safe + epollN" options with a single "safe_epollN" option. It fixes the issue related to the order of these options - if "epollN" comes before "safe" we get a TRC tag that does not match the actual behavior, because safe profile does not overwrite EF_UL_EPOLL variable, but still adds the tag. That breaks epoll tests expectations.
OL-Redmine-Id: 12437
Signed-off-by: Sergey Nikitin <sergey.nikitin@oktetlabs.ru>
---
https://github.com/oktetlabs/sapi-ts/commit/aa418f237334260cab89c70e680543c594372b10
**Testing**:
Running the script:
```bash
$ ./scripts/ool_fix_consistency.sh sfc ef10 epoll3 safe …
```
> scripts: fix epollN + safe options order issue

- sockapi-ts/checksum/tcp_bad_csum_open.c
Wait a little before checking that IUT accept() call is unblocked. Before the patch, we performed this check immediately after sending ACK from Tester. On some systems it might lead to failure with the verdict:
"accept call is still blocked after sending segment with valid checksum"
OL-Redmine-Id: 12655
Signed-off-by: Sergey Nikitin <sergey.nikitin@oktetlabs.ru>
---
https://github.com/oktetlabs/sapi-ts/commit/db90c9048df4492d87132be0289ff1d4b08bd17d
**Testing**
running:
`--tester-run=sockapi-ts/checksum/tcp_bad_csum_open%1*10 --ool=onload --ool=tiny_spin --ool=af_xdp`
The test is green now
> checksum/tcp_bad_csum_open: fix test timing issues

- scripts/ool_fix_consistency.sh
The sfc + af_xdp + zc_af_xdp in network namespaces causes "BUG: kernel NULL pointer: RIP: 0010:efx_xdp".
OL-Redmine-Id: 11986
---------
Testing done:
```
$ ./run.sh --no-item --cfg=my-host --ool=af_xdp --ool=zc_af_xdp --ool=netns_iut
...
RING: af_xdp_fix/SWNETLINUX-4809/Bug 11986: disable netns on SFC NICs with zc_af_xdp: removing --ool=netns_iut
...
```
> scripts: disable netns for the sfc driver with zc_af_xdp

- sockapi-ts/sockopts/package.xml
The test inserts the same hw filter twice, it is incompatible with AF_XDP (at least for now).
OL-Redmine-Id: 12170
Signed-off-by: Sergey Nikitin <sergey.nikitin@oktetlabs.ru>
------
Testing done:
```shell
./run.sh -q --cfg=my-cfg --tester-run=sockapi-ts/sockopts/reuseaddr_tcp_2 --ool=onload --ool=af_xdp
```
The test does not run.
> ts: do not run sockopts/reuseaddr_tcp_2 with AF_XDP

- sockapi-ts/sockopts/tcp_quickack.c
Without this timeout, CSAP does not have time to start, and the test fails with error "ACKs are not sent immediately".
OL-Redmine-Id: 11816
Signed-off-by: Georgii Samoilov <georgii.samoilov@oktetlabs.ru>
--------------
```shell
./run.sh --cfg=<my-cfg> --tester-run=sockapi-ts/sockopts/tcp_quickack%bbd397513c0c925e5f35143a6f9f3d56*10 -n --tester-run-while=expected
```
> sockopts/tcp_quickack: add timeout to wait for CSAP to start

- sockapi-ts/basic/package.xml
Pthread cancellation is not properly supported by Onload.
OL-Redmine-Id: 11774
Signed-off-by: Georgii Samoilov <georgii.samoilov@oktetlabs.ru>
---------
testing done with the following command line:
```shell
./run.sh --cfg=<my-cfg> --ool=onload --tester-req=\!BROKEN --tester-run=sockapi-ts/basic/pthread_cancellation_point
```
> basic/pthread_cancellation_point: disable the test

- sockapi-ts/route/blackhole.c
- sockapi-ts/route/meson.build
- sockapi-ts/route/package.dox
- sockapi-ts/route/package.xml
- trc/trc-sockapi-ts-route.xml
Test add a route of non-usual type and checks that this route is used properly.
OL-Redmine-Id: 12263
Signed-off-by: Daniil Byshenko <daniil.byshenko@oktetlabs.ru>
-----------
testing done:
```sh
$ ./run.sh  -q --cfg=<my-cfg> --tester-run=sockapi-ts/route/blackhole 
$ ./run.sh  -q --cfg=<my-cfg> --tester-run=sockapi-ts/route/blackhole --ool=onload
```
> route: test for blackhole routes and similar

- sockapi-ts/sendrecv/stream_iov_send.c
We have encountered with such fails in nigth test logs:
```
24	RING	sendrecv/stream_iov_send	TAPI RPC	00:32:41.056	RPC (Agt_B,pco_tst[8]): read(7, 0x5596a5c11c20[1024], 1024, chk_func=TRUE) -> 100 (RPC-EBADF)
25	WARN	sendrecv/stream_iov_send	Self	00:32:41.056	Not all data are received
26	RING	sendrecv/stream_iov_send	TAPI RPC	00:32:41.091	RPC (Agt_B,pco_tst[9]): read(7, 0x5596a5c11c84[924], 924, chk_func=TRUE) -> 10 (RPC-EBADF)
27	ERROR	sendrecv/stream_iov_send	Self	00:32:41.091	Length of data received on the TST -1514633555 does not match to length of data sent from IUT
```
We can see that the ERROR message contains a strange negative number. The proposed patch fixes the issue;
To reproduce the failure is quite difficult because there is no consistency.
Anyway, running a cmd:
`./run.sh …
> sockapi-ts/sendrecv: fix logging and wait time to receive remaining data 

- sockapi-ts/gateways_epilogue.c
sfc and i40e drivers do not restore XDP state after down-up thus gateways_epilogue with af_xdp_no_filters + zc_af_xdp parameter combinations on intel/sfc configurations fails and crashes further testing. To avoid crashes in zc_af_xdp cases, we recreate onload stack and restart IUT directly in the test.
OL-Redmine-Id: 12053
Signed-off-by: Pavel Liulchak <pavel.liulchak@oktetlabs.ru>
_______
Testing done:
OpenOnload: 23dfd4873bc66403a3c6315ea2513f9569d23b3e
Open TE: 9df17bb39bfc97797d6edb03e5b68e6f02e2e5e2
The patch is part of https://github.com/oktetlabs/sapi-ts
see [oktetlabs/sapi-ts@438274e1](https://github.com/oktetlabs/sapi-ts/commit/438274e14ecfbe8d5671881e7da02882c837194b)
cmd that shows further tests fail after …
> sockapi-ts: recreate stack and restart IUT

- scripts/gen_onload_part.py
This part should always be ignored for af_xdp_strict mode, regardless of whether af_xdp or af_xdp_no_filters options are present or not.
OL-Redmine-Id: 12768
Fixes: 0be5da288ae9 ("Sapi-TS going public")
-----
Checked with the following command line (with this patch the transparent part disappears):
```shell
$ ./scripts/gen_onload_part.py -a 3558 375 my-cfg master --use-params-file=<path-to-gen-onload-parts.yml> -x
transparent;;IP_TRANSPARENT,!IP6_ONLOAD;pkt_nocomp,hwport2,epoll3,scalable_any,no_rx_ts,bond4,vlan,ipvlan,no_reuse_pco,phys_mode,fw_full_featured,tcp_shared_ports_reuse_fast,tcp_shared_ports,default_pselect,fds_mt_safe,epoll_mt_safe,tcp_no_delack,loop4,d …
```
> scripts: always ignore the transparent part with AF_XDP

- scripts/ool_fix_consistency.sh
tiny-spin mode has been added to simulate a customer who is essentially interested in the low lattency
(High Frequency Trading). AF_XDP doesn't provide
good latency results thus the set af_xdp + tiny_spin has no sense.
OL-Redmine-Id: 12656
Signed-off-by: Pavel Liulchak <pavel.liulchak@oktetlabs.ru>
_____
Testing done:
cmd:
`./run.sh -n --cfg=${my_cfg} --tester-run=sockapi-ts/congestion/app_rtt%ee7e7425cf945916e1c19e9b0328b7dd --ool=onload --ool=af_xdp --log-html=html --sniff-log-conv-disable --ool=tiny_spin`
```
RING: af_xdp_fix/Bug 11802/ON-12446: using --ool=few_stacks
RING: af_xdp_fix/Bug 12656: disable tiny_spin with af_xdp: removing --ool=tiny_spin
...
--->>> Start Tester
Starting package sockapi-ts
Starting test …
```
> scripts: disable tiny-spin if run with af_xdp

- trc/trc-sockapi-ts-multicast.xml
The TRC tag reuse_stack should be used for iomux=oo_epoll iterations, just as it is used for the rest of the iterations of iomux.
OL-Redmine-Id: 11929
Signed-off-by: Georgii Samoilov <georgii.samoilov@oktetlabs.ru>
--------
```shell
./run.sh -n --cfg=<my-cfg> --tester-run=sockapi-ts/multicast/iomux_multicast:env=VAR.env.peer2peer_mcast_lo,iomux=oo_epoll --ool=mcast_send2 --ool=onload
```
> trc: fill in TRC for iomux_multicast:iomux=oo_epoll

- sockapi-ts/reuseport/package.xml
- sockapi-ts/reuseport/reuseport_threaded_iomux.c
- trc/trc-sockapi-ts-reuseport.xml
Checked with the following command line:
```shell
./run.sh -n --cfg=<my-cfg> --ool=onload --ool=scalable_iut --ool=scalable_active_passive \
--ool=no_reuse_pco --tester-run=sockapi-ts/reuseport/reuseport_threaded_iomux
```
> reuseport_threaded_iomux: add parameter late_iomux and fill-in TRC for the test

- sockapi-ts/sockopts/tcp_user_timeout.c
Now TSA_ESTABLISH_PASSIVE flag works as expected for that state.
OL-Redmine-Id: 11581
Signed-off-by: Dmitry Izbitsky <dmitry.izbitsky@oktetlabs.ru>
-----
The test is green now:
```shell
./run.sh --cfg=<my-cfg> --tester-run=sockapi-ts/sockopts/tcp_user_timeout
```
> sockopts/tcp_user_timeout: remove SYN_RECV workaround

- sockapi-ts/sendrecv/package.xml
- sockapi-ts/sendrecv/recvmsg_trunc.c
- trc/trc-sockapi-ts-sendrecv.xml
New parameter 'use_null_buffer' for the test 'recvmsg_trunc': whether to send the message with null buffer
> sendrecv/recvmsg_trunc: add iteration with null buffer

- sockapi-ts/checksum/package.xml
- sockapi-ts/checksum/tcp_bad_csum_close.c
- sockapi-ts/checksum/tcp_bad_csum_conn.c
- sockapi-ts/checksum/tcp_bad_csum_open.c
New parameter value env = env_peer2peer_ipv6 for the tests tcp_bad_csum_close, tcp_bad_csum_conn, tcp_bad_csum_open. Now these tests also have iterations with IPv6 sockets.
In these iterations the parameter 'protocol' is only IPPROTO_TCP, because IPv6 header does not contain checksum
> checksum: add IPv6 iterations

- sockapi-ts/sockopts/package.xml
The affected environment is obviously testing IPv6.
Fixes: 0be5da288ae9 ("Sapi-TS going public")
> sockopts/bindtodevice_dstunreach: add missing IPv6 reqs

- scripts/ool_fix_reqs.py
- scripts/run.sh
`sockapi-ts/route/if_change_netns` is test that uses NETNS requirement and mey crash further runs.
cmd: `./run.sh -q --cfg=host-sfc --tester-run=sockapi-ts/route/if_change_netns --ool=onload --ool=af_xdp --ool=zc_af_xdp --ool=netns_all --log-html=html`
OpenOnload: `54958ab61230c2624a3ffa329fa8aba06d5061c2`
ts-conf:    `b882465e07f7ef510d1df2ca673efa81a49f62d9`
Open TE:    `96847d49d06b0c37092b18950873a40074b8d96f`
logs:
```
RING: af_xdp_fix/SWNETLINUX-4809/Bug 11986: disable netns on SFC NICs with zc_af_xdp: removing --ool=netns_all
...
RING: req_fix: SWNETLINUX-4809/Bug-11986: do not test network namespaces of SFC NICs with zc_af_xdp: adding --tester-req=!NETNS
...
--->>> Starting Logger...done
--->>> Starting RCF...done
--->>> Starting Configurator...done
--->>> Start Tester
--->>> …
```
> scripts: avoid netns testing on SFC NICs with zc_af_xdp

- sockapi-ts/prologue.c
Otherwise, the test may try to change the iptables rules on a non-existent interface.
OL-Redmine-Id: 12871
---------
```shell
./run.sh -n --cfg=<my-host-with-single-interface> --tester-run=sockapi-ts/usecases/read_write --ool=ip_options
```
> prologue: consider an empty interface name as its absence

- sockapi-ts/basic/accept_multiple.c
- sockapi-ts/lib/sockapi-ts_tcp.c
- sockapi-ts/lib/sockapi-ts_tcp.h
Add function sockts_connect_retry() to lib/sockapi-ts_tcp, which is common in several tests. It is used for making many attempts to connect to IUT RPC server, in a loop.
Delete the function test_connect_loop() from basic/accept_multiple. Replace it with sockts_connect_retry(), which is the rewritten version of this function.
> ts: move function to common library place

- sockapi-ts/tcp/package.xml
- sockapi-ts/tcp/tcp_server_restart.c
Remove unnecessary use of SO_REUSEPORT from the test. Using socket option SO_REUSEADDR is enough to bind socket with the same address and port.
AMD-Jira-Id: ST-2697
> tcp/tcp_server_restart: remove SO_REUSEPORT

- sockapi-ts/tcp/tcp_server_restart.c
Setup IUT library name for the second listen socket, because the default one is not what we need by the scenario.
https://github.com/oktetlabs/sapi-ts/commit/8da1ab91eccda8bae23f63433a008372fe958ff7
> tcp/tcp_server_restart: use proper library for IUT pco

- talib_sockapi_ts/syscall_close.S
By default, assembler code in talib leads to process start with executable stack. Modify assembler code to avoid this issue.
OL-Redmine-Id: 12841
---
Testing done:
Open TE: `736841be0cded9f0a98aaef784f81fe887ff6549`
Open Onload: `da11323a6402a2b2392768b619bf2689490b5457`
Before the patch executable stack kernel warning occurred on each first test agent start after host reboot:
```
...
[  616.511803] onload_cp_server[1845]: Accelerating enp2s0f1: RX 2 TX 2
[  825.938888] ICMPv6: process `ta' is using deprecated sysctl (syscall) net.ipv6.neigh.enp2s0f0.retrans_time - use net.ipv6.neigh.enp2s0f0.retrans_time_ms instead
[  854.448843] process '/ta_ubuntu22_kuzandro_734165_1688489031_4/ta_rpcs' started with executable stack …
```
> talib: fix executable stack kernel warning

- sockapi-ts/level5/out_of_resources/out_of_stacks.c
Do not fail on absense of allocate_stack event in the Configurator database while running level5/out_of_resources/out_of_stacks test, because this event may be turned off.
OL-Redmine-Id: 12903
___
Testing done:
Open TE: 1bddac291cbcdb32e3254972ded82ec9a75f1d39
Open Onload: b8998ae559b576616edfa251e4678f30e132514d
If `log_event_allocate_stack` is turned off, the test fails with error:
```
Test Failed in ../../../sapi-ts/sockapi-ts/level5/out_of_resources/out_of_stacks.c, line 86, main() 
line 86: cfg_get_instance_fmt(NULL, &pars_signal, "/local:/tester:/event:allocate_stack" "/handler:internal_handler/signal:") returns 0xF400002 (CS-ENOENT), but expected 0 
```
In this patch …
> level5/out_of_resources: fix allocate_stack event failure

- sockapi-ts/usecases/splice.c
Really disable pipe acceleration by setting EF_PIPE env variable to zero. Simple unsetting the variable is not enough.
---
I checked the patch on Debian-testing with `6.4.0-1-amd64`.
Command line for socket-tester:
```
--tester-run=sockapi-ts/usecases/splice:splice_before_data=FALSE,set_move=FALSE,set_nonblock=FALSE,extra_pipes=0,overfill_pipe=FALSE,acc_pipe=FALSE,diff_stacks=FALSE,pipe_size=unchanged --ool=onload --ool=af_xdp
```
P.S.: so many parameters is to reduce number of iterations.
There're few unexpected results, because  `splice()` returns `EINVAL` on some iterations.
> usecases/splice: fix acc_pipe=FALSE iterations

- sockapi-ts/lib/sockapi-ts.c
- sockapi-ts/lib/sockapi-ts.h
Add functions sockts_iut_netns_setup() and sockts_destroy_netns()
to lib/sockapi-ts. These functions create/delete a net namespace,
Test agent within it, with specified interface added to it. They
are used in several new tests.
> lib: add new library functions for net namespace

- sockapi-ts/basic/diff_ipvlan_macvlan_check.c
- sockapi-ts/basic/meson.build
- sockapi-ts/basic/package.dox
- sockapi-ts/basic/package.xml
- sockapi-ts/doc/sapi_tests.yml
- trc/trc-sockapi-ts-basic.xml
Check that IP VLAN and MAC VLAN do not receive wrong packets.
Create a UDP socket which receives packets from a given *VLAN
interface only: using SO_BINDTODEVICE or inside netns. Check
that the socket only receives packets with correct IP address
(in case IP VLAN) or MAC address (in case MAC VLAN), equal to
the address of the given *VLAN interface.
AMD-Jira-Id: ST-2420
> basic/diff_ipvlan_macvlan_check: implement new test

- sockapi-ts/basic/diff_vlan_check_id.c
- sockapi-ts/basic/meson.build
- sockapi-ts/basic/package.dox
- sockapi-ts/basic/package.xml
- sockapi-ts/doc/sapi_tests.yml
- trc/trc-sockapi-ts-basic.xml
Check that VLAN does not receive wrong packets. Create a UDP socket
which receives packets from a given VLAN interface only: using
SO_BINDTODEVICE or inside netns. Check that the socket only receives
packets with correct VLAN tag, equal to VLAN ID of the given VLAN
interface.
AMD-Jira-Id: ST-2420
> basic/diff_vlan_check_id: implement new test

- sockapi-ts/lib/sockapi-ts.c
- sockapi-ts/lib/sockapi-ts.h
In function sockts_netns_setup_common() in lib/sockapi-ts.c, do not
check that parameter rpcs_ns is not NULL. Specifying a location for
RPC server handle is not required for the server creation. Ignoring
this broke the congestion package.
Fixes: 0f89596c0ddb ("congestion/lib: update function for netns creation on TST")
> lib: allow not to specify rpcs_ns during netns creation

- conf/scripts/sockapi-ts
- scripts/run.sh
Write a comment in the output about ignored headers absence instead of
rsync error.
OL-Redmine-Id: 13098
---
Testing done:
Open TE: 036933085164a20bff7c5d3d21980c196e270b1c
Open Onload: 76e6c7d6d2720a3e62a2bde3502d8bbf87dcd8c3
Different branches may contain different set of extension headers. Absence of headers causes rsync errors:
```
rsync: [sender] link_stat "/home/ol-kuzandro/my_branch/src/include/onload/extensions_zc_hlrx.h" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1819) [Receiver=3.2.3]
rsync: [Receiver] write error: Broken pipe (32)
```
To handle these errors with …
> conf: handle absence of ignored headers

- conf/scripts/copy-onload-headers
- conf/scripts/sockapi-ts
- scripts/run.sh
Copy the set of headers, specific for currently used branch, or create symlinks for them in the script run last.
Run other sockapi configurations before the scripts fixing ool consistency as further executed scripts need exports from sockapi configurations.
Fixes: d74da290255c ("scripts: run sockapi configuration scripts last")
OL-Redmine-Id: 13098
---
Testing done:
Open TE: 036933085164a20bff7c5d3d21980c196e270b1c
Open Onload: 76e6c7d6d2720a3e62a2bde3502d8bbf87dcd8c3
Executing all the scripts from `opts.ts` last has broken bonding, teaming and onload-profile testing.
Reproducer command line:
```
./run.sh --cfg=${my_host_conf} -q --cs-print-trees --cs-log-diff --tester-ignore-run-name \
--trc-log=trc-log.bz2 --trc-tag=no-aio …
```
> scripts: copy branch specific headers set last

- sockapi-ts/doc/sapi_tests.yml
- sockapi-ts/tcp/meson.build
- sockapi-ts/tcp/package.dox
- sockapi-ts/tcp/package.xml
- sockapi-ts/tcp/send_retrans_fail.c
- trc/trc-sockapi-ts-tcp.xml
Check error code/message after TCP send retransmission fails, for
different send functions. The test iterates all the possible send
functions, especially extension ones. It also iterates various ways
for a TCP send retransmission to fail.
AMD-Jira-Id: ST-2535
> tcp/send_retrans_fail: implement new test

- sockapi-ts/tcp/fin_data.c
Give the CSAP time to run before continuing with the testing steps.
OL-Redmine-Id: 13265
----------
```shell
./run.sh --no-builder --cfg=<hostname> \
--tester-run=sockapi-ts/tcp/fin_data:cache_socket=FALSE,env=VAR.env.peer2peer_gw,linger=TRUE,shutdown=FALSE*100 \
--tester-run-while=expected --ool=hwport2 --ool=udp_connect_no_handover --ool=epoll3 --ool=iomux_no_fast --ool=sleep_spin \
--ool=syscall --ool=no_rx_ts --ool=no_reuse_pco --ool=scooby --ool=tcp_shared_ports_reuse_fast --ool=tcp_shared_ports \
--ool=default_poll --ool=loop1 --ool=safe_epoll3 --ool=fdtable_strict --ool=socket_cache --ool=af_xdp_no_filters \
--ool=zc_af_xdp --ool=tcp_combine_send --ool=zc_reg_huge_align --ool=urg_ignore --ool=mcast_send1 --ool=onload \
--ool=reuse_stack …
```
> tcp/fin_data: make sure that CSAP really started

- sockapi-ts/bnbvalue/file_max_overflow.c
- sockapi-ts/tcp/tcp_loopback.c
In the cleanup section the CLEANUP_CHECK_RC macro should be used instead of CHECK_RC.
Fixes: 0be5da288ae9 ("Sapi-TS going public")
-------------
Rebuild is OK.
> sockapi-ts: correctly complete operations in cleanup section

- sockapi-ts/tcp/overfill_close.c
Just give the CSAP time to run before continuing with the testing steps.
OL-Redmine-Id: 13254
-------------
```shell
./run.sh -n --cfg=<my-test-host> --tester-run-while=expected --ool=ssn \
--tester-run=sockapi-ts/tcp/overfill_close:env=VAR.env.peer2peer,shutdown=FALSE,fill_rcv=packet,fill_snd=FALSE,peer_close=FALSE,cache_socket=FALSE*100 
```
> tcp/overfill_close: make sure that CSAP really started

- conf/scripts/sockapi-ts
Use the new dependency for the scripts library: yhe script/lib from the ts-conf repository now uses functions and variables declared in the make_cmds file.
> conf/scripts: use the new dependency for the scripts library

- sockapi-ts/bnbvalue/file_max_overflow.c
- sockapi-ts/lib/sockapi-ts.h
- sockapi-ts/tcp/tcp_loopback.c
There may be situations when a test tries to add a user who already exists on IUT: tests should not fail because of this.
------
The following tests are green now (on test-environment: [d461e193c](https://github.com/oktetlabs/test-environment/commit/d461e193c5b102beb42365ff04e16f5b761a2ea9)):
```console
./run.sh --no-builder --cfg=<host> \
--tester-run=sockapi-ts/basic/bind_sockaddr_send%9520b304c06ff9ff98c02196537a0147 \
--tester-run=sockapi-ts/bnbvalue/file_max_overflow:env=VAR.env.peer2peer,fd_type=tcp_passive,other_user=TRUE \
--tester-run=sockapi-ts/tcp/tcp_loopback%6c9511645b34f2279a6b70782b5784b7
```
> sockapi-ts/lib: do not fail if the user already exists

- sockapi-ts/tcp/send_retrans_fail.c
- trc/trc-sockapi-ts-tcp.xml
Add two verdicts for the test to TRC: for retrans_fail_way=user_timeout
and for send_func=sendmmsg. They describe the expected behavior for the
test if it is run with Onload. In the test, print verdict in the case
of an error after calling send_func().
AMD-Jira-Id: ST-2535
> tcp/send_retrans_fail: add verdicts to TRC

- sockapi-ts/tcp/send_retrans_fail.c
Delete an unused variable, this caused a compilator warning.
Fixes: 806a2b792ba4 ("tcp/send_retrans_fail: implement new test")
AMD-Jira-Id: ST-2535
> tcp/send_retrans_fail: delete unused variable

- sockapi-ts/lib/sockapi-ts.c
In function sockts_netns_setup_common() in lib/sockapi-ts, use network
prefix based on AF_INET address family if no network handle is passed.
This fixes an error in congestion/prologue.
Fixes: d93e0db6ac25 ("lib: fix network prefix getting in library function")
> lib: fix network prefix getting in library function

- scripts/ool_fix_reqs.py
sfc and i40e drivers do not restore XDP state after down-up thus test with af_xdp + zc_af_xdp parameter combinations on intel/sfc configurations fail and crash further testing. We avoid tests with mentioned parameters and IF_DOWN_UP req on i40e and sfc via setting !IF_DOWN_UP req.
OL-Redmine-Id: 12053
-------
Tested with the following command line:
```console
$ ./scripts/ool_fix_reqs.py --ools zc_af_xdp --iut_drv sfc
RING: req_fix: socket caching is disabled: adding --tester-req=!FD_CACHING
RING: req_fix: there are no any scalable filters: adding --tester-req=!SCALABLE
RING: req_fix: the use_chk_funcs option is not specified: adding --tester-req=!CHK_FUNC
RING: req_fix: ON-13696: onload_zc_send() with registered ZC buffer is broken: adding --tester-req=!ONLOAD_ZC_SEND_USER_BUF
RING: …
```
> scripts: turn off IF_DOWN_UP in case of sfc/i40e

- sockapi-ts/arp/permanent_entry_untouched_by_request.c
- sockapi-ts/route/package.xml
- sockapi-ts/sockopts/tcp_info_retransmits.c
- sockapi-ts/tcp/send_retrans_fail.c
This is a set of minor changes in tests related to timeouts and the addition of a missed multicast tester-requirement.
-------------------
Testing done:
```console
./run.sh -n --cfg=<my-cfg> --tester-run-while=expected \
--tester-run=sockapi-ts/arp/permanent_entry_untouched_by_request:env=VAR.env.peer2peer,sock_type=udp_notconn*30
./scripts/run.sh -n --cfg=<my-cfg> --ool=onload --ool=af_xdp --tester-run-while=expected  \
--tester-run=sockapi-ts/sockopts/tcp_info_retransmits%d2ca282bf2781bb13e9f8672cf6b877a*10 
./run.sh -n --cfg=<my-cfg> --ool=onload --ool=no_reuse_pco \
--tester-run=sockapi-ts/tcp/send_retrans_fail:env=VAR.env.peer2peer,send_func=write,retrans_fail_way=rto*10 
./run.sh -n --cfg=<my-cfg> --tester-run=sockapi-ts/route/pbr_oif_src:multicast=TRUE --tester-req=\!MULTICAST
```
> This is a set of minor changes in tests related to timeouts and the addition of a missed multicast tester-requirement.

- trc/trc-sockapi-ts-ifcfg.xml
Accept either of the two results regardless of the parameters. This is acceptable because if there is an unexpected verdict, the test will be red.
-------
The test is green now, I checked the following command lines:
```
./run.sh --n --cfg=<my-host> --tester-run=sockapi-ts/ifcfg/recv_wrong_mac --ool=onload --ool=af_xdp_no_filters
./run.sh --n --cfg=<my-host> --tester-run=sockapi-ts/ifcfg/recv_wrong_mac --ool=onload --ool=af_xdp
./run.sh --n --cfg=<my-host> --tester-run=sockapi-ts/ifcfg/recv_wrong_mac
```
> trc: fix TRC DB for ifcfg/recv_wrong_mac

- trc/trc-sockapi-ts-basic.xml
Fix TRC for 'backlog=-1' iterations. The test results changed after Onload got 'somaxconn' parameter supported.
---
`--tester-run=sockapi-ts/basic/listen_backlog_values --ool=onload` is green with the patches from https://github.com/Xilinx-CNS/onload/pull/182
> basic/listen_backlog_values: update TRC expectations

- sockapi-ts/iomux/peer_close_before_accept.c
- trc/trc-sockapi-ts-basic.xml
The first commit is being checked by running the test on pure Linux and latest OpenOnload:
```console
./run.sh -n --cfg=<my-cfg> --tester-run=sockapi-ts/basic/listen_backlog_values
./run.sh -n --cfg=<my-cfg> --tester-run=sockapi-ts/basic/listen_backlog_values --ool=loop{0,1,2,3,4} --ool=onload
```
And the second one:
```console
./run.sh -n --cfg=<my-cfg> --ool=loop3 --ool=onload --tester-run-while=expected \
--tester-run=sockapi-ts/iomux/peer_close_before_accept%fe66ed4677cd943ad595a946b67de04c*100
```
> Set of improvements: update TRC DB for basic/listen_backlog_values and fix sleeping iomux/peer_close_before_accept

- sockapi-ts/basic/diff_ipvlan_macvlan_check.c
- sockapi-ts/basic/diff_vlan_check_id.c
- sockapi-ts/basic/package.xml
Add iterations with IPv6 env to the tests diff_vlan_check_id and
diff_ipvlan_macvlan_check.
> basic: add IPv6 iterations to the VLAN tests

- sockapi-ts/basic/package.xml
This is necessary so that broken test iteration results do not interfere with the classification of test results. The following test iterations caused an `ci_assert(~lib_context->thread->sig.c.aflags & 0x4)` and were therefore marked as broken.
- threaded_busy_socket, recv iteration;
- threaded_nblock_conn, epoll iteration;
- threaded_udp, epoll iteration.
OL-Redmine-Id: 11794
> basic/threaded: disable several broken test iterations

- talib_sockapi_ts/rpc.c
Also reuse the existing code instead of duplicate it. It prevents the possible SEGFAULTs and the compiler warnings.
OL-Redmine-Id: 13021
> talib/rpc: free the filename after the possible use

- trc/trc-sockapi-ts-ifcfg.xml
Expect that iterations of the if_remove_addr_after_many_conns test can now succeed, this prevents test logs from being clogged with irrelevant results.
OL-Redmine-Id: 11852
> trc: update TRC for ifcfg/if_remove_addr_after_many_conns

- sockapi-ts/basic/package.xml
- sockapi-ts/bnbvalue/package.xml
In too many sockets tests connections are being accepted until the
limit of opened file descriptors in the system is achieved (EMFILE
error). The last (not accepted) connection is saved in accept queue.
Tests close one of the accepted connections and accept the one saved
in the queue.
In case of socket caching, closing one of accepted connections does
not result in the freeing of accept queue and accept() still fails
with EMFILE error.
After Onload started to drop SYN in case of full accept queue, calling
connect() in this case started to result in timeout error. Tests with
many sockets and socket caching began to fail.
All in all, too many sockets tests does not make sense in case of
socket caching, because the accept queue is not freed. That is why this
combination should be turned off. …
> Turn off many sockets + close + caching tests

- log.sh
- scripts/run.sh
1. avoid overwriting metadata by TE (use --no-meta option by default)
2. scripts: improve logs generation
----------------
Tested by rebuild/run the sapi-ts.
> small but useful changes to ./scripts

- scripts/ool_fix_consistency.sh
- sockapi-ts/basic/listen_shutdown_listen.c
- sockapi-ts/ioctls/siocethtool_glink.c
- sockapi-ts/performance/sfnt_pingpong.c
- get rid of the orphaned stacks at the end of the test basic/listen_shutdown_listen
- use the convenient function to wait for interface UP in the sockapi-ts/ioctls/siocethtool_glink
- make the ool_fix_consistency scripts more readable (and updatable)
- get rid of the orphaned stacks before sfnt-pingpong starts
-------------------
Tested by rebuilding the sapi-ts and running the tests manually - all OK.
> The set of minor changes for tests and auxiliary scripts

- sockapi-ts/sockopts/ipv6_only_bind.c
- sockapi-ts/sockopts/package.xml
- trc/trc-sockapi-ts-sockopts.xml
Modify the test based on the change of behavior in Linux 6.1. Add new
iterations, with IPv6 socket bound to an IPv4-mapped address based on
a newly allocated address. Change TRC to account for test verdicts that
occur in previous Linux versions.
> sockopts/ipv6_only_bind: change according to new kernel version

- sockapi-ts/ioctls/fionbio_thread_unblock_send.c
Read all data from the socket on Tester before checking that send()
is unblocked. Use rpc_drain_fd_simple() to achieve this.
> ioctls/fionbio_thread_unblock_send: fix send() error

- conf/scripts/sockapi-ts
The functions from the ts-conf/scripts/lib file now use the te_ta_ssh_helper library from TE.
OL-Redmine-Id: 13706
---------------
Checked by rebuilding sapi-ts:
```console
./run.sh -q --cfg=${CFG} --build-only
```
> conf/scripts: use the additional library from TE

- sockapi-ts/ioctls/fionbio_thread_unblock_send.c
Remove whitespaces from empty lines.
> ioctls/fionbio_thread_unblock_send: remove whitespaces

- sockapi-ts/sockopts/tcp_quickack.c
Enable the option TCP_NODELAY to increase stability of the test.
This resolves unlikely but possible situations when packets are getting
merged, resulting in fewer ACKs.
> sockopts/tcp_quickack: enable TCP_NODELAY

- sockapi-ts/sockopts/tcp_quickack.c
Wait before stopping to receive packets on CSAP to get last ACKs from
IUT. This prevents situations when not all ACKs have enough time to be
captured.
Now the number of ACKs received from IUT in case opt_val=1 (TCP_QUICKACK
enabled) is sufficient.
> sockopts/tcp_quickack: wait for catching all ACKs

- talib_sockapi_ts/rpc.c
This is necessary in order for the sapi-ts to be built after changes in the test-environment repository.
Checked with the following command line `$ ./run.sh -q --cfg=${MYCFG} --build-only` on:
- ts-conf: https://github.com/Xilinx-CNS/cns-ts-conf/commit/a5944c05ccd9e77a1487cb19334df973ff4cd43d
- te: https://github.com/oktetlabs/test-environment/commit/f5a037581a21fc0a44adc2108d7e79604f5d4d93
> talib/rpc: build fix for te_bool deprecation

- sockapi-ts/level5/ext_stackname/meson.build
- sockapi-ts/level5/ext_stackname/move_fd_same_udp.c
- sockapi-ts/level5/ext_stackname/package.dox
- sockapi-ts/level5/ext_stackname/package.xml
- trc/trc-sockapi-ts-level5-ext_stackname.xml
Check that onload_move_fd(), moving UDP socket on IUT to the same
stack, does the right thing. Namely, check that onload_move_fd
returns success, the socket remains in the same stack and functions
normally.
> level5/move_fd_same_udp: implement new test

- sockapi-ts/level5/out_of_resources/out_of_packets.c
Wait longer in rpc_pattern_receiver() to get all the retransmits from tester of the packets which might have been dropped due to "memory pressure" state in Onload.
It fixes potential error:
rpc_pattern_receiver() received unexpected number of bytes on pco_iut
> level5/out_of_packets: adjust pattern receiver parameters

- sockapi-ts/lib/iomux.c
- sockapi-ts/lib/iomux.h
Implement the case IC_EPOLL_PWAIT2 in function iomux_epoll_call and
related functions.
Reviewed-by: Viacheslav Galaktionov <viacheslav.galaktionov@arknetworks.am>
> lib/iomux: implement epoll_pwait2

- sockapi-ts/epoll/event_order.c
- sockapi-ts/epoll/multiple_same_epfd.c
- sockapi-ts/epoll/package.xml
- sockapi-ts/epoll/small_maxevents.c
- sockapi-ts/package.xml
- trc/trc-sockapi-ts-epoll.xml
Add value epoll_pwait2 to enum epoll_wait_calls. Use this value for
parameter of type 'epoll_wait_calls' in all tests in package iomux.
Fill TRC in a similar way to parameter value epoll_pwait.
> sockapi-ts: add epoll_pwait2 to enum epoll_wait_calls

- sockapi-ts/tcp/invalid_ack.c
According to new changes in TE there is no need to treat TCP_TIME_WAIT in a special way.
New changes mean 
https://github.com/oktetlabs/test-environment/pull/67
With this patch tcp/invalid_ack (and all other tcp tests) go as expected.
> tcp/invalid_ack: treat TCP_TIME_WAIT as others TCP states

- trc/trc-sockapi-ts-iomux.xml
> iomux/timeout_update: fix TRC for ppoll

- sockapi-ts/epoll/package.xml
- trc/trc-sockapi-ts-epoll.xml
ioctl() on epfd changed it's behaviour on new kernels.
AMD-Jira-ID: ST-2753
../cns-sapi-ts/run.sh --cfg=... --tester-run=sockapi-ts/epoll/ioctl_on_epfd
> epoll/ioctl_on_epfd: correct expected errno

- sockapi-ts/bnbvalue/func_splice_nonconn_dgram.c
- sockapi-ts/bnbvalue/meson.build
- sockapi-ts/bnbvalue/package.dox
- sockapi-ts/bnbvalue/package.xml
- trc/trc-sockapi-ts-bnbvalue.xml
Check that @b splice() functions correctly handle situation with not connected @c SOCK_DGRAM sockets
AMD-Jira-ID: ST-2746
Reviewed-by: Viacheslav Galaktionov <viacheslav.galaktionov@arknetworks.am>
Testing done:
../cns-sapi-ts/run.sh  --tester-run=sockapi-ts/bnbvalue/func_splice_nonconn_dgram
All pass and green.
../cns-sapi-ts/run.sh  --ool=onload --ool=af_xdp  --ool=no_reuse_pco --tester-run=sockapi-ts/bnbvalue/func_splice_nonconn_dgram
Some failures.
> bnbvalue/func_splice_noncon_dgram: add new test
